# Generated by Django 4.2.9 on 2024-01-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_admin_email_remove_admin_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
