# Generated by Django 4.2.9 on 2024-01-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='art_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='eng_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='is_under_dispute',
            field=models.BooleanField(default=False),
        ),
    ]
