# Generated by Django 4.2.7 on 2024-01-31 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='cover_letter',
        ),
    ]
