# Generated by Django 4.2.7 on 2024-01-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_student_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='finished_link',
            field=models.TextField(default=''),
        ),
    ]
