# Generated by Django 4.2.7 on 2024-02-01 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_job_finished_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='art_approved',
        ),
        migrations.RemoveField(
            model_name='job',
            name='eng_approved',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_under_dispute',
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chosen_side', models.CharField(choices=[('poster', 'Poster'), ('worker', 'Worker')], max_length=7)),
                ('eng_approved', models.BooleanField(default=False)),
                ('art_approved', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputed_job', to='jobs.job')),
            ],
        ),
    ]
