# Generated by Django 4.2.7 on 2024-02-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_remove_job_art_approved_remove_job_eng_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='chosen_side',
            field=models.CharField(choices=[('poster', 'Poster'), ('worker', 'Worker')], default=None, max_length=7, null=True),
        ),
    ]
