# Generated by Django 4.2.7 on 2024-02-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_alter_dispute_chosen_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='was_disputed',
            field=models.BooleanField(default=False),
        ),
    ]
